[meta]
FORMAT_VERSION = "0.1.0"
NAME = "versions"
DESCRIPTION = """
An example of API versioning.

This file specifies v2 of an app which has been updated from v1, removing the route `deleted` and
changing some metadata. The associated tide-disco app serves both versions of the API
simultaneously, under version prefixes.
"""

[route.added]
PATH = ["added"]
DOC = """
This route was added in version 2.
"""
