[meta]
FORMAT_VERSION = "0.1.0"

HTML_TOP = """
<!DOCTYPE html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <title>Title from api.toml</title>
    <link rel='stylesheet' href='public/css/style.css'>
    <script src='public/js/script.js'></script>

    <link rel="icon" type="image/svg+xml"
     href="public/favicon.svg">

  </head>
  <body>
    <div><img src='public/espressosys_logo.svg'
              alt='Espresso Systems Logo'
              /></div>
    <h1>Heading in api.toml</h1>
    <p>Text introducing the collected documentation</p>
"""

HTML_BOTTOM = """
  <h1>Heading at the bottom</h1>
  <p>Text at the bottom. Maybe a copyright notice or link.</p>
  <p>Copyright © 2022 Espresso Systems. All rights reserved.</p>
  </body>
</html>
"""

HEADING_ROUTES = "Routes"
HEADING_PARAMETERS = "Parameters"
HEADING_DESCRIPTION = "Description"

MINIMAL_HTML = """
<!doctype html>
<html lang='en'>
  <head>
    <meta charset='utf-8'>
    <title>Help</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>Help text goes here.</p>
  </body>
</html>
"""

[route.help]
PATH = ["help", "help/:endpoint"]
METHOD = "GET"
":endpoint" = "Literal"
DOC = "Provides complete reference documentation if no endpoint is provided or help on a single endpoint"

[route.healthcheck]
PATH = ["healthcheck"]
METHOD = "GET"
DOC = "Provides server status as JSON such as ```{status: Available}```"
