name: Build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:
env:
  RUSTFLAGS: "--cfg async_executor_impl=\"async-std\" --cfg async_channel_impl=\"async-std\""

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout Repository

      - uses: Swatinem/rust-cache@v2
        name: Enable Rust Caching
        with:
          cache-on-failure: true

      - name: Format Check
        run: cargo fmt -- --check

      - uses: actions-rs/clippy-check@v1
        name: Clippy
        with:
          token: ${{ github.token }}
          args: --workspace --all-features --all-targets -- -D warnings

      - name: Audit
        run: cargo audit --ignore RUSTSEC-2023-0065

      - name: Build
        run: |
          cargo build --workspace --release

      - name: Test
        run: |
          cargo test --workspace --release --all-features --no-run
          cargo test --workspace --release --all-features --verbose -- --test-threads 2
        timeout-minutes: 30

      - name: Generate Documentation
        run: |
          cargo doc --no-deps --lib --release
          echo '<meta http-equiv="refresh" content="0; url=tide_disco">' > target/doc/index.html

      - name: Deploy Documentation
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          cname: tide-disco.docs.espressosys.com
